import pandas as pd
from llm_handler.model_access import prompt_model

def classify_choice_of_law_issue(text, classification_prompt, model):
    prompt_issue_classification = f"""{classification_prompt}
        
                    Here is the text of the Court Decision:
                    {text}
                    """
    return prompt_model(prompt_issue_classification, model)

dictionary = {
    "Theme": [
        "Revision/reform",
        "Comparative method",
        "Persuasive authority",
        "Refer to an instrument",
        "Party autonomy",
        "Respect choice of law clause",
        "Dépeçage",
        "Modification of a choice of law clause",
        "Connection",
        "Neutral law / 'law of a 3rd country'",
        "PIL codification",
        "Connection criteria/factors",
        "non-State law / rules of law",
        "Incorporate rules by way of reference",
        "Express choice",
        "Tacit choice",
        "Mandatory rules",
        "Public policy",
        "Arbitration",
        "Arbitrators vs. State judges",
        "Arbitral awards vs. court decisions",
        "Institutional rules (arbitration)",
        "Absence of choice",
        "Weaker/vulnerable parties",
        "International contracts (commercial)",
        "Conventions/hard law",
        "Principles/soft law",
        "Legislation"
    ],
    "Definition": [
        "A revision or reform in the context of private international law refers to the process of examining existing laws (e.g., Civil Code), regulations (e.g., PIL Act), or legal frameworks (e.g., Principles or rules) and making changes or adaptions to them. Revisions are often minor modifications, while a legal reform describes a more comprehensive change. In private international law, this can be reflected as a new PIL Act or suppression of “outdated” rules. For the purposes of choice of law provisions, jurisdictions might consider or adopt new approaches such as accepting non-State law as a valid choice of law agreement.",
        "The 'Comparative method' refers to a legal approach where laws, legal principles, and court decisions from other jurisdictions are considered and analyzed as part of the decision-making process. When using the comparative method, a judge or arbitrator (or any person applying legal rules) may look at how different legal systems have approached similar legal issues or disputes. The purpose of this method is not to directly apply foreign law to a case, but rather to gain insights, perspectives, or guidance that can inform the interpretation and application of domestic law. The ultimate decision must still be based on and be compliant with the domestic legal system and its principles.",
        "The persuasive authority of a given soft law instrument refers to its capacity to influence courts, lawmakers, and legal practitioners, despite not being legally binding in the same way as hard law (e.g., statutes or treaties). Some important factors that contribute to the persuasive authority of a soft law instrument are the practical utility of the soft law instrument.",
        "When judges 'refer to an instrument' in a legal context, it typically means that they are citing or making reference to a specific legal document or authoritative text in their legal reasoning, decision-making process, or written judgment. This could be a statute, a treaty, a judicial decision, a soft law document (e.g., guidelines or principles), or any other authoritative legal text. The judge then analyzes the content of the instrument by interpreting its provisions, understanding its context, and determining how it applies to the specific facts and legal issues of the case. This may involve drawing analogies, noting differences, or using the instrument to clarify or fill gaps in existing law. The judge uses the instrument to support the legal reasoning, and the reference to the instrument may be documented in the judge’s written opinion or judgment.",
        "Party autonomy refers to the power of the parties to a contract to choose a neutral law or the law they consider most appropriate for their specific contract. It enhances certainty and predictability within the parties’ primary contractual arrangement and recognizes that parties to a contract may be in the best position to determine which set of legal principles is most suitable for their transaction. Many States have reached this conclusion and, as a result, giving effect to party autonomy is the predominant view today. However, there are considerable differences regarding the scope of this concept (e.g., with respect to consumer or employment contracts).",
        "When courts or arbitral tribunals 'respect a choice of law clause,' it means they acknowledge and apply the specific legal system (the law of a particular country or set of rules) that the parties to a contract have agreed upon to govern their contract. This is a fundamental aspect of upholding party autonomy in contract law, especially in international contexts. Courts or arbitral tribunals will normally respect the parties' contractual choice of law clause, provided that the choice of law is made within the limits set out by the applicable law, usually the lex fori or the lex arbitri.",
        "Dépeçage is a private international law concept which refers to the process of applying different legal systems or laws to different issues within the same legal relationship. Instead of applying a single jurisdiction’s laws to all aspects of a case, dépeçage allows dissecting the case and applying different laws to different parts of it, based on the most relevant connections those parts have to particular legal systems. Dépeçage enables the resolution of legal issues by engaging in a choice-of-law analysis on an issue-by-issue basis, but bears the risk of inconsistencies among the various legal systems applied.",
        "A 'modification of a choice of law clause' refers to the process of the parties modifying an existing contractual choice of law clause. A choice of law clause can only be modified with the mutual consent of all parties to the contract. The modification should be made by drafting an amendment to the original contract which specifies the new choice of law.",
        "'Connection' is a link or relationship between a legal issue and a particular jurisdiction or legal system in the context of private international law. Connection criteria are used to ascertain the internationality of a contract and to determine if a link between two systems exists.",
        "A 'neutral law' or the 'law of a third country' describes a choice of law made by the parties, in which they agree on a law to govern their relationship that is not the law of a country directly connected to either party or their relationship (contract) itself. This approach is often used in cross-border agreements where parties are from different countries. Parties often choose the law of a jurisdiction known for its well-established and stable legal system, predictable legal outcomes, and sophisticated commercial law. This helps in avoiding any perceived home advantage and aims to eliminate any potential bias or conflict of interest that might arise from using the law of a country to which one of the parties is connected.",
        "The concept of 'PIL codification' refers to the process of systematically arranging and integrating the rules of private international law into a coherent legal framework or code. This codification is aimed at addressing various aspects of private international law, such as choice of law in international contracts. Codification may involve the consolidation of existing laws, the introduction of new legal principles, and the harmonization of laws to facilitate their application in a global context.",
        "'Connection criteria' refer to the elements or considerations used to establish a link or relationship between a legal issue and a particular jurisdiction or legal system in the context of private international law. These criteria help in determining the most appropriate law or jurisdiction to govern a particular legal issue, especially in cases involving international elements. For example, the concept of 'establishment' is often used as a connecting factor in various jurisdictions to ascertain the internationality of a contract and to determine the law applicable to the parties' agreement on choice of law.",
        "'Non-State law or rules of law' refers to regulations that are generally accepted on an international, supranational, or regional level as a neutral and balanced set of rules. These can include non-binding instruments formulated by established international bodies, such as the UNIDROIT Principles of International Commercial Contracts (UPICC). Arbitration statutes and rules often permit contractual disputes to be resolved under such 'rules of law.'",
        "Incorporating rules by way of reference in an international commercial contract means that the parties explicitly agree to be bound by certain rules or laws that are not detailed in the contract itself but are referenced within it. This allows for the inclusion of comprehensive legal frameworks, industry standards, or technical specifications without the need to spell out all the details in the contract, simplifying the document while ensuring that the referenced rules are legally binding. For example, a contract might state that it is governed by 'INCOTERMS' (a set of commercial/trade rules established by the International Chamber of Commerce) without reproducing those rules in the contract. These rules become part of the contractual terms agreed between the parties. As per the HCCH Principles, incorporation by reference is different from allowing parties to choose 'rules of law' as the law applicable to their contract.",
        "An 'express choice' of law is a clear and explicit choice of law stated by the parties, typically in contractual provisions. It reflects the principle of party autonomy, acknowledging that parties are best positioned to select the legal system most suitable for their transaction. This express choice is widely recognized across various international, supranational, and national legal frameworks, albeit within certain limits, such as those imposed by public policy and overriding mandatory rules.",
        "A 'tacit choice of law' is a not explicitly stated choice of law, which can be inferred from contractual provisions or the circumstances surrounding the parties’ agreements. While a tacit choice stems from the principle of party autonomy, it requires clear evidence from the contract or its circumstances, indicating that the parties intended a specific legal system to govern their contract.",
        "Overriding mandatory rules can be defined as mandatory rules that are crucial for the countries’ economic, social and political purposes, and their application is required for the disputes within their scope. These rules are always applied independently of the parties’ choice of law. They are often associated with the lex fori, although some authors also refer to lex causae’s rules as mandatory rules.",
        "Public policy in private international law refers to the fundamental principles or values that a country considers essential to its legal system and societal values. A court may refuse to apply a foreign law if it is found to be contrary to the public policy of the forum. This ensures that certain core principles of justice, morality, or social order are upheld in legal proceedings. The public policy exception serves as a safeguard against the enforcement of foreign laws that could undermine or violate a country's fundamental legal or ethical standards.",
        "Arbitration is an alternative dispute resolution method where parties to a dispute agree to resolve their issues outside of the traditional court system, usually through an arbitrator or panel of arbitrators. In international contexts, arbitration is commonly used to address cross-border commercial disputes, providing a neutral and private forum for resolution. Arbitration has distinct rules and practices that differ from those in court, offering parties the opportunity to select arbitrators with expertise in the relevant field and to tailor procedures to the specifics of the dispute.",
        "Arbitrators and State judges play different roles in the resolution of disputes. Arbitrators are chosen by parties to resolve a specific dispute, typically through a private, out-of-court process. They are not part of the formal judiciary and often have specialized knowledge in the area of the dispute. In contrast, State judges are public officials appointed or elected to apply national law in the judicial system, and their decisions are subject to the rules and appeals processes established by the state.",
        "Arbitral awards and court decisions are both legal determinations, but they differ in the authority and recognition given to them. An arbitral award is a binding decision issued by an arbitrator or an arbitral tribunal, while a court decision is a legally binding judgment issued by a court. In many jurisdictions, arbitration awards can be enforced similarly to court judgments, but they are generally not subject to the same appeals processes. The distinction lies in the public versus private nature of their adjudication and the differences in the procedural protections provided.",
        "Institutional rules are a set of rules established by arbitration institutions to govern the procedures of arbitration. These rules provide a framework for the arbitration process, including rules on the appointment of arbitrators, the conduct of hearings, the submission of evidence, and the issuance of awards. Institutional rules ensure consistency and structure in the arbitration process, and parties who choose to arbitrate under an institution typically agree to follow these rules as part of their arbitration agreement.",
        "In cases where there is an absence of a choice of law by the parties, courts and tribunals rely on private international law principles to determine the applicable law. This often involves analyzing the parties' intentions, the nature of the contract, or the location of performance. The decision of applicable law seeks to provide legal certainty while respecting the reasonable expectations of the parties. The absence of choice triggers the application of default rules in private international law, which vary based on the jurisdiction and the type of contract.",
        "Weaker or vulnerable parties in international contracts, such as consumers and employees, are often afforded special protections under private international law. The principle of protecting weaker parties recognizes the power imbalance that may exist between individual consumers or employees and large corporations or employers. In some jurisdictions, mandatory rules protect the rights of these parties, limiting the application of choice of law clauses that would otherwise disadvantage them.",
        "International contracts in a commercial context refer to legally binding agreements between parties from different countries engaged in trade, investment, or other business activities. Private international law addresses issues such as jurisdiction, choice of law, and enforcement in these cross-border contracts, which involve complex interactions of legal systems. International contracts often incorporate choice of law clauses to manage these complexities and promote legal certainty.",
        "International conventions, also known as 'hard law,' are legally binding agreements established between countries. These conventions address issues in private international law, such as choice of law, jurisdiction, and the recognition and enforcement of judgments in cross-border cases. Examples include the United Nations Convention on Contracts for the International Sale of Goods (CISG) and various Hague Conventions. Conventions play a significant role in harmonizing private international law across jurisdictions.",
        "Principles, often referred to as 'soft law,' include non-binding guidelines or standards created by international organizations, private entities, or academic groups. While not enforceable like laws or treaties, these principles provide guidance and influence legal practices. Examples of such principles include the UNIDROIT Principles of International Commercial Contracts and the Principles of European Contract Law, which courts and arbitrators may refer to as persuasive authority.",
        "Legislation in the context of private international law refers to the statutory laws enacted by a legislative body that govern aspects of private international law, including choice of law, jurisdiction, and enforcement of judgments in cross-border cases. Legislation varies by jurisdiction but is essential in establishing rules for the resolution of disputes with an international element, particularly when parties have not specified their preferred legal system."
    ]
}

def extract_choice_of_law_issue(text, classification_prompt, prompt, model):
    classification = classify_choice_of_law_issue(text, classification_prompt, model)
    print("This court decision has been classified as: ", classification)
    prompt_issue = f"""{prompt}
                The issue in this case is related to this theme: {classification}
    
                Here is the text of the Court Decision:
                {text}
                """
    return prompt_model(prompt_issue, model)
